### ISSUE TITLE
Modulus version?

### ISSUE THREAD

**Issue by ThomasLecat** [neo-fetch/nvidia-modulus-airfoil-optimisation#3]
Hi @neo-fetch , 

I am trying to run the basic command found in the README after installing modulus:

```bash
python src/ldc_2d.py --layer_size 100 --nr_layers 2
```
but I get:

```bash
Traceback (most recent call last):
  File "src/ldc_2d.py", line 3, in <module>
    from modulus.variables import Variables
ModuleNotFoundError: No module named 'modulus.variables'
```

Can you specify which version of modulus you are using?

Many thanks!

**Comment by neo-fetch** [comment]
Hey thomas! I'm using version 21.06

**Comment by neo-fetch** [comment]
Hey Thomas, were you able to find the version? I have a feeling that version is not available for download anymore...

**Comment by neo-fetch** [comment]
@ThomasLecat we have shifted to version 22.07. Please find the code in the relevant folder.
